"""The ONE definition of the tile set.

land_tiles(), home_tiles() and port_tiles() describe every physical tile. build_design.py draws them into
bga/img/tiles/ (the single place tile art lives; BGA and print use those exact files) and writes
bga/modules/php/tileset.json, which the server reads to deal tiles. A tile carries its own data: resource, building
sockets, road mask (6 chars, order = Game.php DIRS: right, up-right, up-left, left, down-left, down-right).
BGA never draws on top of a tile; it only adds coordinates outside the board.

Run this file directly to test that random deals give connected boards.
"""
import json
import math
import os
import random

GOODS = ('iron', 'crystal', 'bot', 'mech')
KINDS = ('cheaper', 'pays_more')
DIRS = [(1, 0), (1, -1), (0, -1), (-1, 0), (-1, 1), (0, 1)]
FACTION_COLORS = [('red', 'c0392b'), ('blue', '2980b9'), ('green', '27ae60'), ('yellow', 'e1b12c'), ('purple', '8e44ad'), ('orange', 'd35400')]

# which land tiles hold two resources (so the "Rich Land" missions can be completed): (level, number)
DOUBLE = {(2, 5), (3, 3), (3, 9), (4, 7)}


def land_tiles(seed=7):
    """37 land tiles: 1 centre (level 1), 6 level 2, 12 level 3, 18 level 4."""
    rng = random.Random(seed)
    tiles = []
    for level, count in [(1, 1), (2, 6), (3, 12), (4, 18)]:
        for n in range(1, count + 1):
            x = rng.randint(1, 4)
            res = None if x == 1 else ('iron' if x <= 3 else 'crystal')
            if (level, n) in DOUBLE:
                res = 'double'
            if level == 1:
                slots = 2
            elif level == 2:
                slots = rng.randint(1, 2)
            else:
                y = rng.randint(1, 4)
                slots = 0 if y == 1 else (1 if y <= 3 else 2)
                if res is None:
                    slots = max(1, slots)
            if res == 'double':
                slots = max(slots, 1)
            lo, hi = {1: (6, 6), 2: (5, 6)}.get(level, (4, 5))
            open_dirs = set(rng.sample(range(6), rng.randint(lo, hi)))
            mask = ''.join('1' if d in open_dirs else '0' for d in range(6))
            tiles.append({'kind': 'land', 'code': f'L{level}-{n:02d}', 'art': f'land_L{level}_{n:02d}', 'level': level,
                          'res': res, 'slots': slots, 'mask': mask})
    return tiles


def home_tiles():
    """One per faction colour. All six roads open so a home always joins the board (its neighbours decide)."""
    return [{'kind': 'home', 'code': f'H{i}', 'art': f'home_{i}_{name}', 'color': hexcol, 'res': 'iron', 'slots': 2, 'mask': '111111'}
            for i, (name, hexcol) in enumerate(FACTION_COLORS, start=1)]


def port_combos():
    return [(g, k) for g in GOODS for k in KINDS]


def port_tiles():
    """Every good x kind x side. Side k = the land is on edges k and k+1 (a port always touches exactly 2 land tiles)."""
    out = []
    for ci, (good, kind) in enumerate(port_combos(), start=1):
        for k in range(6):
            mask = ''.join('1' if d in (k, (k + 1) % 6) else '0' for d in range(6))
            out.append({'kind': 'port', 'code': f'P{ci}', 'art': f'port_{good}_{kind}_s{k}', 'good': good, 'port_kind': kind,
                        'side': k, 'res': None, 'slots': 0, 'mask': mask})
    return out


def manifest():
    return {'land': land_tiles(), 'home': home_tiles(), 'port': port_tiles(), 'combos': [list(c) for c in port_combos()]}


def write_manifest(path):
    """Writes a PHP file (deploys like any code file) that returns the manifest as an array."""
    data = json.dumps(manifest(), indent=1)
    with open(path, 'w') as f:
        f.write("<?php\n// GENERATED by design/build_design.py from design/tileset.py. Do not edit by hand.\nreturn json_decode(<<<'JSON'\n" + data + "\nJSON, true);\n")


# ---------------- connectivity test (mirrors the server's dealing) ----------------

def _positions(radius):
    land = [(q, r) for q in range(-radius, radius + 1) for r in range(-radius, radius + 1) if abs(-q - r) <= radius]
    outer = radius + 1
    spots = [(q, r) for q in range(-outer, outer + 1) for r in range(-outer, outer + 1)
             if max(abs(q), abs(r), abs(-q - r)) == outer and sum(1 for a in (abs(q), abs(r), abs(-q - r)) if a == outer) == 1]
    return land, spots


def _angle(q, r):
    return math.atan2(1.5 * r, math.sqrt(3) * (q + r / 2))


def deal_once(radius, players, rng, land_set, homes, with_ports=True):
    """Returns (hexes dict (q,r)->mask, connected bool)."""
    land, spots = _positions(radius)
    ring = lambda q, r: max(abs(q), abs(r), abs(-q - r))
    by_level = {lv: [t for t in land_set if t['level'] == lv] for lv in (1, 2, 3, 4)}
    for lv in by_level:
        rng.shuffle(by_level[lv])
    perimeter = sorted([p for p in land if ring(*p) == radius], key=lambda p: _angle(*p))
    home_pos = {perimeter[int(i * len(perimeter) / players)] for i in range(players)}
    masks = {}
    used = {lv: 0 for lv in by_level}
    for (q, r) in land:
        if (q, r) in home_pos:
            masks[(q, r)] = '111111'
            continue
        lv = ring(q, r) + 1
        masks[(q, r)] = by_level[lv][used[lv]]['mask']
        used[lv] += 1
    if with_ports:
        spots = sorted(spots, key=lambda p: _angle(*p))
        count = 2 * players
        for p in range(count):
            q, r = spots[int((p + 0.5) * len(spots) / count) % len(spots)]
            dirs = [d for d, (dq, dr) in enumerate(DIRS) if (q + dq, r + dr) in masks and ring(q + dq, r + dr) <= radius]
            k = dirs[0] if (dirs[1] - dirs[0]) == 1 else dirs[1]
            masks[(q, r)] = ''.join('1' if d in (k, (k + 1) % 6) else '0' for d in range(6))
    seen = {(0, 0)}
    queue = [(0, 0)]
    while queue:
        q, r = queue.pop()
        for d, (dq, dr) in enumerate(DIRS):
            n = (q + dq, r + dr)
            if n in masks and n not in seen and masks[(q, r)][d] == '1' and masks[n][(d + 3) % 6] == '1':
                seen.add(n)
                queue.append(n)
    return masks, len(seen) == len(masks)


def success_rate(radius, players, trials=3000, with_ports=True):
    rng = random.Random(1)
    land, homes = land_tiles(), home_tiles()
    ok = sum(1 for _ in range(trials) if deal_once(radius, players, rng, land, homes, with_ports)[1])
    return ok / trials


if __name__ == '__main__':
    for radius, players in [(2, 2), (2, 3), (3, 4), (3, 6)]:
        print(f'radius {radius}, {players} players: connected deals {success_rate(radius, players):.1%} (with ports), {success_rate(radius, players, with_ports=False):.1%} (no ports)')
